### ISSUE TITLE
Unable to flash firmware on new RZRAVEN USB stick

### ISSUE THREAD

**Issue by GoogleCodeExporter** [riverloopsec/killerbee#33] opened 2015-03-24 11:20 UTC
```
Hello all,

I'm trying to flash the killerbee firmware on two RZRAVEN sticks I recently 
purchases (hardware rev. E) using the mkii jtag programmer. Unfortunately I'm 
having some difficultly. AVR studio claims it programs successfully, however, 
when it powers back up the LED is solid red and the USB device is not 
recognized. Even lsusb does not show the device.  This issue is present for 
both of the sticks I recently purchased. However, I have an older stick (rev A) 
which programs and works fine.  Has anyone experienced anything like this with 
newer sticks? Also, is the firmware binary in svn a recent build? I have not 
attempted to build from source yet but that will likely be the next step.  
Thanks in advance!

What steps will reproduce the problem?
1. Program RZRAVEN USB stick with firmware binary from SVN using mkii jtag 
programmer.
2. Power on USB stick, LED solid red

What version of the product are you using?
KillerBee beta (from SVN checkout) Revision # 99

On what operating system? Windows 7 on Virtualbox (Ubuntu host OS).



```

Original issue reported on code.google.com by `phil.beh...@gmail.com` on 20 Mar 2015 at 1:30

**Comment by joswr1ght** [comment] 2015-04-24 13:40
I'm afraid I have not seen this issue before - the solid red LED is not a great sign!  I just updated the README file in the git repository with updated instructions using the AVR Dragon and AVRDUDE.

Maybe try flashing from Linux using AVRDUDE and your mkII or pick up a cheap AVR Dragon and use the mkII 50mm-100mm standoff adapter you already have?  You should still be able to flash the device, even if it's not recognized by Linux or Windows through the USB interface.

-Josh

**Comment by QuantumTheory** [comment] 2015-05-28 21:20
I had the same issue, seems to be caused by some mismatch in the eeprom, If you build killerbee from source after changing EE_MAGIC from 0x42 to 0xFF in include/arch/avr/eep.h it seems to fix the problem. I'm still looking for a better solution though. Also the Makefile is in gcc/RZUSBSTICK, you will need to change the includes line in that one, it contains some windows directory paths. I found that doing a find and replace for C:\dev\KillerBee-Firmware\gcc replacing with ../ and then doing a find for \ and replacing with / works well. (This is all in linux with avr-gcc installed)

**Comment by EastL** [comment] 2015-06-12 02:51
@QuantumTheory  Thank you very much!!!!

**Comment by ridingintraffic** [comment] 2015-06-23 02:27
would you be able to share that compiled hex file? i am having issues compiling from source with the same issue

**Comment by riverloopsec** [comment] 2015-06-29 03:06
@QuantumTheory - Thanks for the suggestion here - very interesting.
Given that two other people have also had the issue, I think it would make sense to have a branch with three updates:
1) the edited EE_MAGIC
2) the fixed Makefile
3) the resultant hex file
Would you be willing to submit a PR with those changes?

**Comment by ridingintraffic** [comment] 2015-06-29 16:05
i have forked the repo and checked in my changes that should close the firmware issue and also issue #37 since i compiled it against Ubuntu.   Take a look and verify my work before you merge it into main.
https://github.com/ridingintraffic/killerbee/commits/master

**Comment by riverloopsec** [comment] 2015-07-05 17:25
Thanks @ridingintraffic. I don't have newer RZUSB hardware to test this on, but I've looked at the changes and they look minimal and logical. I merged to bugfix/33-rzusb-fw for now and added documentation. As this is a non-breaking change (the old HEX file is still there), I'm going to merge to master and close this ticket.

If anyone has issues with kb-rzusbstick-002.hex, please let us know here!

**Closed by riverloopsec** 2015-07-05 17:25 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect

**Comment by QuantumTheory** [comment] 2015-07-08 19:36
Just for reference, it appears that this was caused by atmel not flashing the eeprom at the factory, as further investigation has revealed that the entire section is just FF over and over. This also means that the mac addy burned into the device is FF:FF:FF:FF:FF:FF, not that it matters much for KB. (sorry I didn't see your posts sooner, apparently my notification email setting was out of date)
